# ==============================================================================
# DAG: core_bootstrap
# Descrição: Configuração inicial do repositório Core e ambiente de execução
# Objetivo: Deploy do repositório Core, instalação de dependências e configuração do ambiente (.env)
# Agendamento: Semanalmente, toda segunda-feira às 2h da manhã (UTC) 
# ==============================================================================
from airflow import DAG
from airflow.operators.bash import BashOperator
from datetime import datetime, timedelta
import pendulum

local_tz = pendulum.timezone("America/Sao_Paulo")

default_args = {
    'owner': 'squad3-ops',
    'depends_on_past': False,
    'start_date': datetime(2026, 2, 10, tzinfo=local_tz),
    'retries': 0,
}

with DAG(
    'core_bootstrap',
    default_args=default_args,
    description='Bootstrap do Repositório Core e Configuração de Ambiente (.env)',
    schedule_interval='0 2 * * 1',
    catchup=False,
    tags=['core', 'deploy'],
    max_active_runs=1,
) as dag:

    sync_core = BashOperator(
        task_id='sync_core_repository',
        bash_command="""
            git config --global --add safe.directory /opt/airflow/core && \
            export GIT_SSH_COMMAND="ssh -i /home/airflow/.ssh/id_ed25519 -o StrictHostKeyChecking=no" && \
            cd /opt/airflow/core && \
            git fetch origin main && \
            git reset --hard origin/main && \
            git clean -fd && \
            git pull origin main || echo "Core atualizado com ressalvas"
        """,
    )

    setup_core_env = BashOperator(
        task_id='setup_core_environment',
        bash_command="""
cat << EOT > /opt/airflow/core/.env
# --- AUTO GENERATED BY OPS BOOTSTRAP ---
S3_ENDPOINT=${OCI_S3_ENDPOINT}
AWS_ACCESS_KEY_ID=${OCI_ACCESS_KEY}
AWS_SECRET_ACCESS_KEY=${OCI_SECRET_KEY}
AWS_DEFAULT_REGION=${OCI_REGION}

# Configurações de Hardware (DuckDB)
DUCKDB_MEMORY_LIMIT=48GB
DUCKDB_THREADS=12

# Política de Retenção
BRONZE_MAX_RUNS=1
SILVER_MAX_RUNS=1
GOLD_MAX_RUNS=1
EOT
        """,
    )

    install_deps = BashOperator(
        task_id='install_core_dependencies',
        bash_command="""
        set -e
        if [ -f /opt/airflow/core/requirements.txt ]; then
            echo "Requirements file found. Setting up virtual environment..."
            
            python -m venv /opt/airflow/core/venv
            
            source /opt/airflow/core/venv/bin/activate
            
            pip install --upgrade pip
            pip install -r /opt/airflow/core/requirements.txt
            
            echo "Dependências instaladas com sucesso em /opt/airflow/core/venv"
        else
            echo "Sem requirements no core"
        fi
        """,
    )

    set_permissions = BashOperator(
        task_id='set_pipeline_permissions',
        bash_command='chmod +x /opt/airflow/core/bin/run_pipeline.sh || true',
    )

    sync_core >> setup_core_env >> install_deps >> set_permissions