from airflow import DAG
from airflow.operators.bash import BashOperator
from datetime import datetime, timedelta

default_args = {
    'owner': 'squad3-core',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'retries': 0,
}

with DAG(
    'dag_core_bootstrap',
    default_args=default_args,
    description='Bootstrap do Repositório Core e Configuração de Ambiente (.env)',
    schedule_interval=None,
    catchup=False,
    tags=['core', 'setup'],
) as dag:

    sync_core = BashOperator(
        task_id='sync_core_repository',
        bash_command='cd /opt/airflow/core && git pull origin main || echo "Core já atualizado"',
    )

    setup_core_env = BashOperator(
        task_id='setup_core_environment',
        bash_command="""
        cat << EOT > /opt/airflow/core/.env
            # --- AUTO GENERATED BY OPS BOOTSTRAP ---
            S3_ENDPOINT=${OCI_S3_ENDPOINT}
            AWS_ACCESS_KEY_ID=${OCI_ACCESS_KEY}
            AWS_SECRET_ACCESS_KEY=${OCI_SECRET_KEY}
            AWS_DEFAULT_REGION=${OCI_REGION}

            # Configurações de Hardware (DuckDB)
            DUCKDB_MEMORY_LIMIT=16GB
            DUCKDB_THREADS=6

            # Política de Retenção
            BRONZE_MAX_RUNS=1
            SILVER_MAX_RUNS=1
            GOLD_MAX_RUNS=1
            EOT
        """,
    )

    install_deps = BashOperator(
        task_id='install_core_dependencies',
        bash_command='pip install -r /opt/airflow/core/requirements.txt || echo "Sem requirements no core"',
    )

    set_permissions = BashOperator(
        task_id='set_pipeline_permissions',
        bash_command='chmod +x /opt/airflow/core/bin/run_pipeline.sh',
    )

    sync_core >> setup_core_env >> install_deps >> set_permissions